import { NextResponse } from "next/server";

import { getStaffSession } from "@/src/server/auth/session";
import {
  getAnalyticsSummary,
  getDashboardMetrics,
  getRevenueByMethod,
  getRevenueSeries,
  getSubscriptionMix,
} from "@/src/server/services/analytics";
import { isDatabaseConfigured } from "@/src/server/env";

export const dynamic = "force-dynamic";

/** RFC 4180 quoting: a field containing a comma, quote or newline must be quoted. */
function csvCell(value: string | number | null | undefined): string {
  const text = value === null || value === undefined ? "" : String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function csvRows(rows: (string | number | null)[][]): string {
  return rows.map((row) => row.map(csvCell).join(",")).join("\r\n");
}

export async function GET(request: Request) {
  const session = await getStaffSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (!isDatabaseConfigured()) {
    return NextResponse.json({ error: "Database not configured" }, { status: 503 });
  }

  const type = new URL(request.url).searchParams.get("type") ?? "dashboard";
  if (type !== "dashboard") {
    return NextResponse.json({ error: "Unknown export type" }, { status: 400 });
  }

  const [metrics, summary, mix, revenue, byMethod] = await Promise.all([
    getDashboardMetrics(),
    getAnalyticsSummary(),
    getSubscriptionMix(),
    getRevenueSeries(12),
    getRevenueByMethod(),
  ]);

  const rows: (string | number | null)[][] = [
    ["Bizovix commercial report"],
    ["Generated", new Date().toISOString()],
    ["Generated by", `${session.user.name} <${session.user.email}>`],
    [],
    ["Overview", "Value"],
    ["Total companies", metrics.totalCompanies],
    ["Active companies", metrics.activeCompanies],
    ["Trial companies", metrics.trialCompanies],
    ["Active licenses", metrics.activeLicenses],
    ["Active devices", metrics.activeDevices],
    ["Downloads this month", metrics.downloadsThisMonth],
    ["Expiring in 7 days", metrics.expiringIn7Days],
    [`Revenue this month (${metrics.currencyCode})`, metrics.revenueThisMonth],
    [],
    ["Recurring revenue", "Value"],
    ["MRR", summary.mrr.toFixed(2)],
    ["ARR", summary.arr.toFixed(2)],
    ["Lifetime settled revenue", summary.lifetimeRevenue.toFixed(2)],
    ["Paying companies", summary.paidCompanies],
    [],
    ["Subscription mix", "Count"],
    ["Monthly", mix.monthly],
    ["Yearly", mix.yearly],
    ["Perpetual", mix.perpetual],
    ["Trial", mix.trial],
    [],
    ["Funnel (directional — downloads are anonymous)", "Value"],
    ["Downloads", summary.downloads],
    ["Activations", summary.activations],
    ["Activation rate %", summary.activationRate.toFixed(1)],
    [],
    ["Month", "Subscription revenue", "One-time revenue", "Total"],
    ...revenue.map((point) => [
      point.month,
      point.subscription.toFixed(2),
      point.oneTime.toFixed(2),
      point.total.toFixed(2),
    ]),
    [],
    ["Payment method", "Payments", "Total"],
    ...byMethod.map((row) => [row.method, row.count, row.total.toFixed(2)]),
  ];

  // BOM so Excel opens UTF-8 correctly instead of mangling non-ASCII names.
  const body = `﻿${csvRows(rows)}`;
  const filename = `bizovix-commercial-report-${new Date().toISOString().slice(0, 10)}.csv`;

  return new NextResponse(body, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
